@rootURL = http://localhost:5214/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMDA2Iiwic3ViIjoic21zbUFkbWluIiwiZW1haWwiOiJzbXNtQGFkbWluLmNvbSIsImp0aSI6ImZiNTRiYzQyLTZjOWYtNGQ1Mi1iMDNkLTA4NDI0YjgwOWFiYSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTc1NzE3MTI0OCwiZXhwIjoxNzU3MTc0ODQ4LCJpYXQiOjE3NTcxNzEyNDgsImlzcyI6ImVjb21tZXJjZS1hcGkiLCJhdWQiOiJlY29tbWVyY2UtY2xpZW50In0.FsIcgUHAV4kMqGGEb8Ple-c5-0RcTIyUesiD203QSfM
POST {{rootURL}}/auth/register
Content-Type: application/json

{
  "username": "smsm",
  "firstName": "Abdelrahman",
  "lastName": "Alsammany", 
  "password": "123456",
  "email": "smsm@nu.com",
  "dateOfBirth": "2003-09-05"
}

###
POST {{rootURL}}/auth/register-admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "smsmAdmin",
  "firstName": "Abdelrahman",
  "lastName": "Alsammany", 
  "password": "123456",
  "email": "smsm@admin.com",
  "dateOfBirth": "2003-09-05"
}

### CUSTOMER
POST {{rootURL}}/auth/login
Content-Type: application/json

{
  "username": "smsm",
  "password": "123"
}

### ADMIN
POST {{rootURL}}/auth/login
Content-Type: application/json

{
  "username": "smsmAdmin",
  "password": "123456"
}

### SUPER ADMIN
POST {{rootURL}}/auth/login
Content-Type: application/json

{
  "username": "smsmSuperAdmin",
  "password": "123456"
}

###
POST {{rootURL}}/auth/register
Content-Type: application/json

{
  "username": "test",
  "firstName": "test",
  "lastName": "test", 
  "password": "123456",
  "email": "test@nu.com",
  "dateOfBirth": "2000-01-01"
}

###
GET  {{rootURL}}/users/smsm
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{rootURL}}/merchants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pizza King"
}

###
GET {{rootURL}}/merchants/search?name=pizza
Authorization: Bearer {{token}}

###
GET {{rootURL}}/merchants/1/categories
Authorization: Bearer {{token}}

### Get all products
GET {{rootURL}}/products
Authorization: Bearer {{token}}

### Get all products filtered by category
GET {{rootURL}}/products?category=Pizza
Authorization: Bearer {{token}}

### Search all products
GET {{rootURL}}/products/search?searchTerm=pizza
Authorization: Bearer {{token}}

### Get products for a specific merchant
GET {{rootURL}}/products/merchant/1
Authorization: Bearer {{token}}

### Get products for a specific merchant filtered by category
GET {{rootURL}}/products/merchant/1?category=Pizza
Authorization: Bearer {{token}}

### Search products for a specific merchant
GET {{rootURL}}/products/merchant/1/search?searchTerm=pizza
Authorization: Bearer {{token}}

### Create a new product
POST {{rootURL}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pepperoni Pizza",
  "price": 10.99,
  "categoryId": 1,
  "merchantId": 1,
  "status": 3
}

### Update a product
PUT {{rootURL}}/products/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2,
  "name": "Deluxe Pepperoni Pizza",
  "price": 12.99,
  "categoryId": 1,
  "status": 3
}

### Delete a product
DELETE {{rootURL}}/products/3
Authorization: Bearer {{token}}

### Create category
POST {{rootURL}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pizza"
}