@rootURL = http://localhost:5214/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzbXNtIiwiZW1haWwiOiJzbXNtQG51LmNvbSIsImp0aSI6IjFkYTQwMjliLTM3ZTgtNGQxNi04Y2VkLWEzYmMyMzEzZGFjZSIsInJvbGUiOiJDdXN0b21lciIsIm5iZiI6MTc1Njk0MzM4NywiZXhwIjoxNzU2OTQ2OTg3LCJpYXQiOjE3NTY5NDMzODcsImlzcyI6ImVjb21tZXJjZS1hcGkiLCJhdWQiOiJlY29tbWVyY2UtY2xpZW50In0.bTLgN02_uDqAY3X0KbBTO06aplriapC0auVJXM3l3ng
GET {{rootURL}}

###
POST {{rootURL}}/auth/register
Content-Type: application/json

{
  "username": "smsm",
  "firstName": "Abdelrahman",
  "lastName": "Alsammany", 
  "password": "123456",
  "email": "smsm@nu.com",
  "dateOfBirth": "2003-09-05"
}

###
POST {{rootURL}}/auth/login
Content-Type: application/json

{
  "username": "smsm",
  "password": "123"
}

###
POST {{rootURL}}/auth/register
Content-Type: application/json

{
  "username": "test",
  "firstName": "test",
  "lastName": "test", 
  "password": "123456",
  "email": "test@nu.com",
  "dateOfBirth": "2000-01-01"
}

###
GET  {{rootURL}}/user/smsm
Content-Type: application/json
Authorization: Bearer {{token}}
